### ISSUE TITLE
Lines that share stations

### ISSUE THREAD

**Issue by alorma** [vbarbaresi/MetroGit#3]
Hi.

In Barcelona we have some metro lines that share some stations, since they split in a few in other stations:

example:
- Line 6:
  - Pl. Catalunya
  - Provença
  - Gràcia
  - St. Gervasi (shared with Pl. Molina)
  - Muntaner
  - Ganduxer
  - La Bonanova
  - Sarria
  - Reina Elisenda (some trains go there, others just to Sarria)
- Line 7:
  - Pl. Catalunya
  - Provença
  - Gràcia
  - Pl Molina (shared with St. Gervasi)
  - Padua
  - Putxet
  - Av. Tibidabo

So.... the first 3 stations should share a  branch? Or they should have a branch for each one?

Thanks :D

**Comment by vbarbaresi** [comment]
Hi!

Each line always has its own branch
But they will share the first 3 commits, and diverge only after

I just did the beginning so you can see what it looks like on `gitk --all`:
![untitled-2](https://cloud.githubusercontent.com/assets/5553380/14492259/7b868688-017e-11e6-8690-5bec9885811a.png)

**Comment by alorma** [comment]
Ok that's what i thought

So, create a 6 branch, 3 commits, and then branch named 7?

**Comment by vbarbaresi** [comment]
Yes exactly, or a 7-branch then 6-branch, the result will be the same
Good luck with this!

**Comment by alorma** [comment]
Thanks :) You can close the issue :)
